#!/usr/bin/env bash

sinks=$(pacmd list-sinks | grep "index")

default_i=$(echo "$sinks" | grep "*" | cut -d: -f2)
default_line_n=$(echo "$sinks" | grep -n "*" | cut -c1-1)

total_sinks=$(echo "$sinks" | wc -l)

if [ "$default_line_n" == "$total_sinks" ]; then
	default_i=$(echo "$sinks" | head -1 | cut -d: -f2)
else
	default_i=$(echo "$sinks" | head -n $(("$default_line_n" + 1)) | tail -1 | cut -d: -f2)
fi


$(pactl set-default-sink $(echo "$default_i"))

input_sinks=$(pacmd list-sink-inputs | grep "index" | cut -d: -f2)
echo "$input_sinks" | while read -r input ; do
	$(pacmd move-sink-input "$input" "$default_i")
done
