#!/usr/bin/env bash

echo "Cycling audio sink..."


sinks=$(pacmd list-sinks | grep "index")

default_i=$(echo "$sinks" | grep "*")
default_i=$(echo "${default_i: -1}")
#default_line=$(echo "$SINKS" | grep -n "*" | cut -c1-1) #Index may not be same as line?
total_sinks=$(echo "$sinks" | wc -l)

echo "sinks:"
echo "$sinks"
echo "default_i:"
echo "$default_i"
echo "total_sinks:"
echo "$total_sinks"

if [ "$default_i" == "$total_sinks" ]; then
	echo "Wrapping default"
	default_i=1
else
	echo "Incrementing default"
	default_i=$(("$default_i" + 1))

fi

$(pactl set-default-sink "$default_i")
sinks=$(pacmd list-sinks | grep "index")
	
echo "sinks:"
echo "$sinks"
echo "default_i:"
echo "$default_i"

test=$(pacmd list-sink-inputs | grep "index" | cut -d: -f2)
echo "$test" | while read -r input ; do
	$(pacmd move-sink-input "$input" "$default_i")
done

echo "Finished."


